languague: python
dist: xenial
sudo: true

python:
  - 3.10

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

services:
  postgresql

addons:
  postgresql: '9.5'

install:
  - pip install pipenv
  - pipenv sync -d
  - pip install -r requirements.txt codecov

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - pytest --cov
  - pipenv run pytest --cov=pypro
  - cp contrib/env-sample .env

after_success:
  - pipenv run codecov