languague: python
dist: xenial
sudo: true

python:
  - 3.10

services:
  postgresql

addons:
  postgresql: '9.5'

install: 
  - pip install -r requirements.txt codecov

before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres

script:
  - pytest --cov
  - pipenv run pytest --cov=pypro
  - cp contrib/env-sample .env

after_success:
  - pipenv run codecov